import GameClass
import sys

Items:list = [
    GameClass.Weapon(
        "双手剑",   
        3,
        20        
    ),
    GameClass.WearableArmor(
        "精良的护甲",
        2,
        0
        ),
    GameClass.WearableArmor(
        "光滑的护甲",
        1,
        0.2
    ),
    GameClass.SpecialItem(
        "HP恢复药",
        1,
        20,
        "HealthUP",
        3,
        [GameClass.Player],
        4              
    ),
    GameClass.SpecialItem(
        "技能冷却加速剂",
        1,
        10,
        "CoolDownUP",
        0,
        [GameClass.Player],
        1        
    ),
    GameClass.Weapon(
        "因果剑",
        1.5,
        15
    ),
    GameClass.Item(
        "硬币",
        True,
        1,
        sys.maxsize
    )    
]

Monsters:list[GameClass.Monster] = [
    GameClass.Monster
    (
        "史莱姆",
        5,
        0,
        2,
        0.5,
        False,
        []
    ),
    GameClass.Monster
    (
        "红史莱姆",
        5,
        0,
        2,
        0.5,
        False,
        []
    ),
    GameClass.Monster
    (
        "蓝史莱姆",
        5,
        0,
        2,
        0.5,
        False,
        []
    ),
    GameClass.Monster
    (
        "哥布林",
        15,
        1,
        5,
        0,
        False,
        [],
        1
    ),
    GameClass.Monster
    (
        "精英哥布林",
        20,
        3,
        6.5,
        0.05,
        False,
        [],
        1
    ),
    GameClass.Monster
    (
        "兽人",
        20,
        4,
        8,
        0,
        False,
        [],
        1
    ),
    GameClass.Monster
    (
        "精英兽人",
        30,
        5,
        12,
        0,
        False,
        [],
        1
    ),
    GameClass.Monster
    (
        "史莱姆王",
        50,
        2.5,
        10,
        0.75,
        True,
        [],
        1
    ),
    GameClass.Monster
    (
        "龙",
        100,
        5,
        15,
        0,
        True,
        [],
        1
    )
]

MapAreas:dict[str,float] = {"草原":0.3,"平原":0.3,"火山":0.1,"冰原":0.1,"沙漠":0.05,"城市":0.15} # 区域 : 进入概率
MapEvents:dict[str,dict[str,float]] = {
    "草原":{"宝箱事件":0.2,"前辈":0.2,"阿哈玩偶":0.3,"动物聚会":0.1,"坎诺特":0.2},
    "平原":{"坎诺特":0.2,"前辈":0.2,"史莱姆群":0.4,"阿哈玩偶":0.2},
    "火山":{"灼伤":0.3,"史莱姆群":0.4,"前辈":0.3},
    "冰原":{"冻伤":0.3,"史莱姆群":0.4,"前辈":0.2,"北极熊":0.1},
    "沙漠":{"缺水":0.3,"前辈":0.5,"昏厥":0.3},
    "城市":{"坎诺特":0.4,"普通商人":0.4,"卫兵打劫":0.2}
}
EventMonsters:dict[str,GameClass.Monster] = {
    "宝箱事件":GameClass.Monster(
        "宝箱怪",
        30,
        5,
        10,
        0,
        False,
        [
            GameClass.Skill("宝箱护盾","DodgeUp",1,["Monster"],0.9,4),
            GameClass.Skill("强力撕咬","AttackUp",1,["Player"],2.5,4)
        ],
    ),
    "北极熊":GameClass.Monster(
        "北极熊",
        35,
        5,
        15,
        0,
        False,
        [
            GameClass.Skill("强力击","AttackUp",1,["Monster"],1.75,5),
            GameClass.Skill("震慑","ArmorDown",3,["Player"],0.75,3),
            GameClass.Skill("防护强化","ArmorUp",3,["Monster"],1.5,2)
        ]
    )
}